export const DEFAULT_PAGE_NUMBER = 1;
export const DEFAULT_PAGE_SIZE = 10;
export const HALF_DEFAULT_PAGE_SIZE = 5;
export const DEFAULT_FEE = 100000;
export const DOLLAR_DECIMALS = 2;
export const ZERO_DOLLAR_DECIMALS = 0;
export const TOTAL_ACTIVITY = 5;
export const TOTAL_VEHARBOR_ACTIVITY = 4;
export const DEFAULT_CHAIN_ID_FOR_CLAIM_AIRDROP = 1;
export const PRODUCT_ID = Number(process.env.REACT_APP_HARBOR_APP_ID);
export const CSWAP_APP_ID = Number(process.env.REACT_APP_CSWAP_APP_ID); // for testnet appId is 1, and for devnet appId is 2
