export const chainNetworks = {
    boli: {
        chainId: "boli-1",
        chainName: "Boli Hub",
        rpc: "http://52.194.247.216:26657/",
        rest: "http://52.194.247.216:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "BOLI",
        coinMinimalDenom: "uboli",
        coinDecimals: 6,
        prefix: "boli",
        coinType: 118,
    },
    parallel: {
        chainId: "parallel-1",
        chainName: "Parallel Chain",
        rpc: "http://43.207.145.169:26657/",
        rest: "http://43.207.145.169:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "PARALLEL",
        coinMinimalDenom: "uparallel",
        coinDecimals: 6,
        prefix: "parallel",
        coinType: 118,
    },
    six: {
        chainId: "six-1",
        chainName: "Six Seasons",
        rpc: "http://54.178.60.55:26657/",
        rest: "http://54.178.60.55:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "SIX",
        coinMinimalDenom: "usix",
        coinDecimals: 6,
        prefix: "six",
        coinType: 118,
    },
    hdc: {
        chainId: "hdc-1",
        chainName: "HDC",
        rpc: "http://18.179.118.8:26657/",
        rest: "http://18.179.118.8:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "hdc",
        coinMinimalDenom: "uhdc",
        coinDecimals: 6,
        prefix: "hdc",
        coinType: 118,
    },
};