export const chainNetworks = {
    agoric: {
        chainId: "agoric-3",
        chainName: "Agoric",
        rpc: "https://airdrop.zenscape.one/agoric-rpc",
        rest: "https://airdrop.zenscape.one/agoric-api",
        explorerUrlToTx: "https://bigdipper.live/agoric/transactions/{txHash}",
        coinDenom: "BLD",
        coinMinimalDenom: "ubld",
        coinDecimals: 6,
        prefix: "agoric",
        coinType: 564,
    },
    injective: {
        chainId: "injective-1",
        chainName: "Injective v1.1",
        rpc: "https://airdrop.zenscape.one/injective-rpc",
        rest: "https://airdrop.zenscape.one/injective-api",
        explorerUrlToTx: "https://explorer.injective.network/transaction/{txHash}",
        coinDenom: "INJ",
        coinMinimalDenom: "inj",
        coinDecimals: 18,
        prefix: "inj",
        coinType: 60,
    },
    luna2: {
        chainId: "phoenix-1",
        chainName: "Terra 2.0",
        rpc: "https://airdrop.zenscape.one/luna-rpc",
        rest: "https://airdrop.zenscape.one/luna-api",
        explorerUrlToTx: "https://finder.terra.money/mainnet/tx/{txHash}",
        coinDenom: "LUNA",
        coinMinimalDenom: "uluna",
        coinDecimals: 6,
        prefix: "terra",
        coinType: 330,
        coinGeckoId: "terra-luna-2"
    },
    cronos: {
        chainId: "crypto-org-chain-mainnet-1",
        chainName: "Cronos",
        rpc: "https://rpc.cosmos.directory/cryptoorgchain",
        rest: "https://rest.cosmos.directory/cryptoorgchain",
        explorerUrlToTx: "https://www.mintscan.io/crypto-org/txs/{txHash}",
        coinDenom: "CRO",
        coinMinimalDenom: "basecro",
        coinDecimals: 8,
        prefix: "cro",
        coinType: 394,
    },
    evmos: {
        chainId: "evmos_9001-2",
        chainName: "Evmos",
        rpc: "https://airdrop.zenscape.one/evmos-rpc",
        rest: "https://airdrop.zenscape.one/evmos-api",
        explorerUrlToTx: "https://www.mintscan.io/evmos/txs/{txHash}",
        coinDenom: "EVMOS",
        coinMinimalDenom: "aevmos",
        coinDecimals: 18,
        prefix: "evmos",
        coinType: 60,
    },
    secret: {
        chainId: "secret-4",
        chainName: "Secret Network",
        rpc: "https://rpc.scrt.network",
        rest: "https://api.scrt.network",
        explorerUrlToTx: "https://www.mintscan.io/secret/txs/{txHash}",
        coinDenom: "SCRT",
        coinMinimalDenom: "uscrt",
        coinDecimals: 6,
        prefix: "secret",
        coinType: 529,
    },
    persistence: {
        chainId: "core-1",
        chainName: "Persistence",
        rpc: "https://persistence-rpc.polkachu.com",
        rest: "https://persistence-api.polkachu.com",
        explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "XPRT",
        coinMinimalDenom: "uxprt",
        coinDecimals: 6,
        prefix: "persistence",
        coinType: 750,
    },
    comdex: {
        chainId: "test-1",
        chainName: "Comdex",
        // rpc: "https://rpc.comdex.one",
        // rest: "https://rest.comdex.one",
        rpc: "https://devnet.rpc.comdex.one",
        rest: "https://devnet.rest.comdex.one",
        explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "CMDX",
        coinMinimalDenom: "ucmdx",
        coinDecimals: 6,
        prefix: "comdex",
        coinType: 118,
    },
    boli: {
        chainId: "boli-1",
        chainName: "Boli Hub",
        rpc: "http://52.194.247.216:26657/",
        rest: "http://52.194.247.216:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "BOLI",
        coinMinimalDenom: "uboli",
        coinDecimals: 6,
        prefix: "boli",
        coinType: 118,
    },
    parallel: {
        chainId: "parallel-1",
        chainName: "Parallel Chain",
        rpc: "http://43.207.145.169:26657/",
        rest: "http://43.207.145.169:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "PARALLEL",
        coinMinimalDenom: "uparallel",
        coinDecimals: 6,
        prefix: "parallel",
        coinType: 118,
    },
    six: {
        chainId: "six-1",
        chainName: "Six Seasons",
        rpc: "http://54.178.60.55:26657/",
        rest: "http://54.178.60.55:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "SIX",
        coinMinimalDenom: "usix",
        coinDecimals: 6,
        prefix: "six",
        coinType: 118,
    },
    hdc: {
        chainId: "hdc-1",
        chainName: "HDC",
        rpc: "http://18.179.118.8:26657/",
        rest: "http://18.179.118.8:1317/",
        // explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "hdc",
        coinMinimalDenom: "uhdc",
        coinDecimals: 6,
        prefix: "hdc",
        coinType: 118,
    },
};
